In [2]:
from torch import nn
from torch.utils.data import DataLoader
from torchvision import transforms, datasets
import numpy as np
import pandas as pd

In [ ]:
class NeuralNetwork:
    def __init__(self, *args):
        self.layers = args
    
    def __call__(self, x):
        print(f"X : {x.shape}")
        for i in range(len(self.layers)):
            x = self.layers[i](x)
        return np.argmax(x)
    
    class Layer:
        def __init__(self, in_features = None, out_features = None, bias = True, activation = "None"):
            if activation == "None" and (in_features == None or out_features == None):
                raise KeyError("Features not set for Layer!")


            activation_functions = {"None" : None, "Sigmoid" : (lambda x : 1 / (1 + np.exp(-x))), "Softmax" : (lambda x, axis = 0 : np.exp(x) / np.sum(np.exp(x), axis = 0)), "ReLU" : (lambda x : np.where(x > 0, x, 0)), "Leaky ReLU" : lambda x, alpha = 0.05 : np.where(x > 0, x, x * alpha)}
            

            self.weights = None
            self.bias = None
            self.__dict = {activation}

            self.activation = activation_functions[activation]

            if activation == "None":
                self.weights = np.random.rand(in_features,out_features)
                self.bias = np.zeros(shape = out_features)
                if bias:
                    self.bias = np.random.rand(1,out_features)

                self.__dict = {"Weight" : self.weights,
                            "Bias" : self.bias}

        def __call__(self, *args):
            if self.activation != None:
                print((self.activation)(*args))                
                return (self.activation)(*args)
            else:
                print(np.add(np.matmul(*args,self.weights), self.bias))
                return np.add(np.matmul(*args,self.weights), self.bias)

                    
        
        def state_dict(self):
            return self.__dict
        
    def state_dict(self):
        self.__dict = {}
        for i in range(len(self.layers)):
            self.__dict[f"Layer {i}"] = self.layers[i].state_dict()
        
        return self.__dict
    
    def state_shape(self):
        self.__dict = {}
        for i in range(len(self.layers)):
            try:
                self.__dict[f"Layer {i}"] = {"Weight" : self.layers[i].state_dict()["Weight"].shape, "Bias" : self.layers[i].state_dict()["Bias"].shape}
            except:
                self.__dict[f"Layer {i}"] = self.layers[i].state_dict()
        
        return self.__dict
    
    def summary(self):
        self.__dict = {"Start" : f"1 x {list(self.state_shape()["Layer 0"]["Weight"])[0]}",
                       "End" : f"1 x {list(self.state_shape()[f"Layer {len(self.layers) - 2}"]["Weight"])[1]}"
                       }
        
        return self.__dict


In [8]:
ai = NeuralNetwork(
    NeuralNetwork.Layer(3,6), 
    NeuralNetwork.Layer(activation= "ReLU"), 
    NeuralNetwork.Layer(6,8),
    NeuralNetwork.Layer(activation= "ReLU"), 
    NeuralNetwork.Layer(8,4),
    NeuralNetwork.Layer(activation= "ReLU"), 
    NeuralNetwork.Layer(4,3),
    NeuralNetwork.Layer(activation= "Softmax"), 
    )

In [11]:
ai.state_dict()

{'Layer 0': {'Weight': array([[0.83295021, 0.55807225, 0.08913012, 0.63889773, 0.61989414,
          0.81746958],
         [0.76715413, 0.17659085, 0.86615534, 0.37397355, 0.74447902,
          0.78743708],
         [0.30468322, 0.19323952, 0.51458901, 0.30371949, 0.72464142,
          0.60977887]]),
  'Bias': array([[0.27890242, 0.64538268, 0.27802477, 0.91732768, 0.27886213,
          0.65984711]])},
 'Layer 1': {'ReLU'},
 'Layer 2': {'Weight': array([[0.99437426, 0.4696569 , 0.6115722 , 0.66510507, 0.06242813,
          0.22696378, 0.07596211, 0.09049214],
         [0.43612794, 0.34942923, 0.0571313 , 0.08621275, 0.44574755,
          0.78607537, 0.58370412, 0.33473864],
         [0.47820277, 0.3462535 , 0.49247014, 0.79446737, 0.85565747,
          0.45292856, 0.72905598, 0.62386383],
         [0.5992564 , 0.75252725, 0.88496186, 0.67357964, 0.44654615,
          0.28957286, 0.57531994, 0.3211039 ],
         [0.66730973, 0.66808695, 0.71410237, 0.13711187, 0.01661197,
          0.8

In [12]:
x = np.random.uniform(low = 0, high = 1, size = (1,3))

ai(x)

X : (1, 3)
[[1.82887225 1.42530704 1.47637002 2.01459551 2.0307004  2.50016958]]
[[1.82887225 1.42530704 1.47637002 2.01459551 2.0307004  2.50016958]]
[[7.10790813 5.14529826 8.12418955 5.09064259 4.11631778 5.72110273
  6.32274367 6.92244034]]
[[7.10790813 5.14529826 8.12418955 5.09064259 4.11631778 5.72110273
  6.32274367 6.92244034]]
[[21.99345921 31.8072453  24.33878613 32.94267865]]
[[21.99345921 31.8072453  24.33878613 32.94267865]]
[[68.57406305 79.2068095  51.08125602]]
[[1. 1. 1.]]


0